# Generated by Django 5.0.2 on 2024-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism familiya ')),
                ('group', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], max_length=255, verbose_name='Sinfi')),
                ('school', models.CharField(max_length=255, verbose_name='Maktabi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Tel. raqami')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
