# Generated by Django 5.0.2 on 2024-02-16 17:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='full_name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=255, verbose_name='Sinfi'),
        ),
    ]
